# These brand names should be carefully picked because if the NER model identifies them as brands, only products containing these in the brand field will be returned.
brands = ['ryzen pc', 'intel pc', 'value-top', 'teclast', 'hp', 'aoc',
       'walton', 'lenovo', 'dell', 'smart', 'asus', 'acer', 'msi',
       'apple mac mini', 'macbook', 'chuwi', 'dahua', 'infinix',
       'deepcool', 'pc power', 'maxgreen', 'arctic', 'ekwb',
       'vertical graphics card holder', 'cooler master', 'netac',
       'huntkey', 'gamdias', 'xtreme', 'ram (laptop)', 'g.skill',
       'corsair', 'hikvision', 'orico', 'colorful', 'nzxt', 'transcend',
       'ocpc', 'team', 'lexar', '1stplayer', 'miphi', 'kingston',
       'golden field', 'gigasonic', 'viewsonic', 'trendsonic', 'xiaomi',
       'npc', 'samsung', 'lg', 'philips', 'realview', 'benq', 'monitor',
       'aiwa', 'marsriva', 'power guard', 'digital x', 'kstar',
       'power pac', 'apollo', 'prolink', 'vertiv', 'santak', 'ups', 'ips',
       'zigor', 'tcl', 'xtra', 'nokia', 'symphony', 'zte', 'benco',
       'tecno', 'vivo', 'realme', 'honor', 'oppo', 'oneplus', 'iphone',
       'umidigi', 'amazon', 'black shark', 'huion', 'ipad', 'ribbon',
       'epson', 'starink', 'power print', 'g&g', 'print-rite',
       'true trust', 'safeway', 'brother', 'canon', 'pantum', 'deli',
       'telephone set', 'action camera', 'sjcam', 'ausek', 'akaso',
       'instant camera', 'ordro', 'dji', 'handycam', 'gopro', 'insta360',
       'sony', 'nikon', 'fujifilm', 'panasonic', 'zkteco', 'uniview',
       'jovision', 'entrance control', 'nexakey', 'tp-link', 'tenda',
       'others', 'portable wifi camera', 'imou', 'ezviz', 'faceplate',
       'patch cord', 'connector', 'networking', 'bijoy', 'for home user',
       'cloud solutions', 'microsoft windows', 'for business users',
       'microsoft office', 'adobe', 'mail server solution', 'autodesk',
       'database server solution', 'vmware', 'red hat', 'anydesk',
       'dateup', 'toten', 'cote', 'safenet', 'synology', 'das storage',
       'asustor', 'server ssd', 'hpe', 'cisco', 'server power supply',
       'usb converter', 'audio converter', 'usb cable', 'type-c cable',
       'havit', 'fantech', 'hdmi converter', 'cable organizer',
       'type-c converter', 'hdmi cable', 'lightning cable', 'audio cable',
       'daily lifestyle', 't-wolf', 'displayport converter',
       'printer cable', 'micropack', 'bluetooth receiver',
       'headphone stand', 'vga cable', 'yison', 'oraimo', 'riversong',
       'foneng', 'casio', 'motorola', 'awei', 'joyroom', 'baseus',
       'zoook', 'energizer', 'hoco', 'jbl', 'onikuma', 'edifier', 'wiwu',
       'redragon', 'gamepad', 'steelseries', 'playstation', 'xbox', 'vr',
       'xtrike me', 'logitech', 'rapoo', 'games', 'xtrfy',
       'akash digital tv', 'haier', 'singer', 'daewoo', 'rowa', 'hisense',
       'charger fan', 'electric kettle', 'room heater', 'rice cooker',
       'iron', 'air fryer', 'induction cooker', 'shameem', 'ceiling fan',
       'gree', 'vision']